### ISSUE TITLE
Perl errors when trying to use tool, Mac OS Yosemite and Ruby 2.0.0-p247

### ISSUE THREAD

**Issue by noahgibbs** [bhb/rack-perftools_profiler#29]
I can start the profiler via the **start** URL and then run requests fine, then stop it. But when I try to view the **data** URL, I get Perl errors:

Running the command 'bundle exec pprof.rb --gif /private/var/folders/xd/k4cggzwd3gg9by03qt2mcl5jnp8jjx/T/rack_perftools_profiler.prof' exited with status 1
Using local file /Users/noah.gibbs/.rvm/rubies/ruby-2.0.0-p247/bin/ruby.
Using local file /private/var/folders/xd/k4cggzwd3gg9by03qt2mcl5jnp8jjx/T/rack_perftools_profiler.prof.
substr outside of string at /Users/noah.gibbs/.rvm/gems/ruby-2.0.0-p247/gems/perftools.rb-2.0.1/bin/pprof line 3543.
Use of uninitialized value in string eq at /Users/noah.gibbs/.rvm/gems/ruby-2.0.0-p247/gems/perftools.rb-2.0.1/bin/pprof line 3543.
substr outside of string at /Users/noah.gibbs/.rvm/gems/ruby-2.0.0-p247/gems/perftools.rb-2.0.1/bin/pprof line 3545.
Use of uninitialized value in string eq at /Users/noah.gibbs/.rvm/gems/ruby-2.0.0-p247/gems/perftools.rb-2.0.1/bin/pprof line 3545.
/private/var/folders/xd/k4cggzwd3gg9by03qt2mcl5jnp8jjx/T/rack_perftools_profiler.prof: header size >= 2**16

**Comment by bhb** [comment]
Can you confirm it's not an issue with perftools.rb itself? Can you see if you can successfully generate profiling data via [these instructions](https://github.com/tmm1/perftools.rb#usage-from-ruby). Thanks!

**Comment by noahgibbs** [comment]
When I run the command on the command line that was being run by the /__data__ URL I get the same result. So it's really quite likely it's an issue with Perftools itself.

However, the test programs at the link you gave seem to work without error.

**Comment by bhb** [comment]
That's interesting.

I have seen problems in the past where the data file (`rack_perftools_profiler.prof`) didn't have enough data to actually extract a useful visualization. Ideally, if that happened, `pprof.rb` would give a useful message, but I have seen cases where it just crashes. I haven't seen that specific error message before, but it's my best guess at this point.

Can you try two things?

1. Instead of navigating to `/__data__` can you instead go to `/__data__?printer=text`. I wonder if the issue is generating the gif or if any data extraction has the problem.

2. Can you [set the mode](https://github.com/bhb/rack-perftools_profiler#options) to `:walltime` and then visit a endpoint where you've added a `sleep` to force a long execution time. Then go to `/__data__` with both the text and gif printer.

**Comment by noahgibbs** [comment]
At this point, I no longer have the example set up. However, it's very unlikely (in that specific case) that the problem was too little data, in the sense of just not running for long enough.

**Comment by bhb** [comment]
Darn. Well, unfortunately, I'm out of ideas. I'm confident that the middleware is making calls to `perftools.rb` correctly, so I'm guessing it's a bug in `perftools.rb` with your specific data.

I appreciate you reporting this, but I'm not sure what else to do that this point. I'm going to close now.
